name: isoimagewriter

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.env.os }}
    strategy:
      matrix:
        qt:
          - version: 5.15.2

	env:
	  - name: win64
            os: windows-latest
            ninja_platform: win
            qt_platform: windows
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            pack: 1

    steps:
	- name: Checkout repository
	  uses: actions/checkout@v3

	- name: Install Qt
    	    uses: jurplel/install-qt-action@v2.13.0
    	    timeout-minutes: 10
    	    version: ${{ matrix.qt.version }}
            target: desktop
            host: ${{ matrix.env.qt_platform }}
            arch: ${{ matrix.env.qt_arch }}
            nstall-deps: true
        
        - name: Setup MSVC environment
            with:
              arch: ${{ matrix.env.msvc_arch }}
        
        - name: Configure Release
          run: |
          mkdir -p build
          cd build
          cmake -DROSA_BRANDING=ON ../

	- name: Build
    	  run: |
            cd build
            make
